
version: '3.8'
services: 
  server:
    container_name: api-server
    image: node:14
    environment:
      PORT: '8081'
      HOST: 'localhost'
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/TNO_SIM_DB'
    ports:
      - '8081:8081'
    volumes:
      - ./server:/server
    entrypoint: /bin/sh /server/src/init.sh
  database:
    container_name: postgres-db
    image: postgres
    restart: always 
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'TNO_SIM_DB'
    volumes:
      - ./db-data:/var/lib/postgresql/data
