
version: '3.8'
services: 
  server:
    build: .
    # bless this thread https://stackoverflow.com/questions/52942913/docker-compose-docker-entrypoint
    command: >
      sh -c "npm i && 
        npx prisma generate --schema=./prisma/schema.prisma && 
        npx prisma migrate dev --name init 
        npm start
      "
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
      DATABASE_URL: 'postgresql://postgres:postgres@database:5432/TNO_SIM_DB'
    ports:
      - '80:3000'
    volumes:
      - ./server:/server
    depends_on:
      - database

  database:
    image: postgres
    restart: always 
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'TNO_SIM_DB'
    volumes:
      - ./db-data:/var/lib/postgresql/data
