
@host = http://127.0.0.1:3000

###
post {{host}}/simulation/user
Content-Type: application/json

{
    "firstname":"joshua",                         
    "lastname":"gamer",                 
    "additio":"the",
    "role":"TRAINEE"    
}
###
put {{host}}/simulation/user
Content-Type: application/json

{
    "id":"b00fbc67-5546-40ab-b202-a2ffd2880ed8",
    "addition":"the"            
}
###
get {{host}}/simulation/user


# Logica verder schrijven
# api-calls testen
# OpenAPI-swagger documenteren van apicalls
# Make public server