
@host = http://127.0.0.1:3000

###
post {{host}}/simulation/user
Content-Type: application/json

{
    "firstname":"mathew",                         
    "lastname":"gamer",                 
    "addition":"the",
    "role":"TRAINEE"    
}
###
put {{host}}/simulation/user
Content-Type: application/json

{
    "id":"ac89db60-898e-4059-b7eb-77c1fa8b11b4"
}

# "ac89db60-898e-4059-b7eb-77c1fa8b11b4"
# "289a3445-4aed-4dbd-8c72-2db85566ca1d"
# "b00fbc67-5546-40ab-b202-a2ffd2880ed8"

###
get {{host}}/simulation/user
Content-Type: application/json

{
    "keywords":{
        "where":{
            "id":"ac89db60-898e-4059-b7eb-77c1fa8b11b4"
        },
        "select":{
            "id":true,
            "firstname":true,
            "lastname":true
        }
    }
}
###
delete {{host}}/simulation/user
Content-Type: application/json

{
    "id":"4962856a-071f-4051-8b9e-772368fc6f24"
}
###
post {{host}}/simulation/session
Content-Type: application/json

{
    "description":"Temporary dummy session2."                     
}
###
get {{host}}/simulation/session
###
get {{host}}/simulation/session
Content-Type: application/json

{
    "keywords":{
        "where":{
            "id":"0926a1bf-181d-413f-b9c4-b2ea9df9f72d"
        },
        "include":{
            "participants":{
                "select":{
                    "id":true
                }
            },
            "events":true
        }
    }
}


###
post {{host}}/simulation/scene
Content-Type: application/json

{
    "name":"Arbitrary scene name",                         
    "description":"dummy scene",                 
    "session_id":"0926a1bf-181d-413f-b9c4-b2ea9df9f72d"
}

###
get {{host}}/simulation/scene


###
post {{host}}/simulation/evidence
Content-Type: application/json

{
    "x":5,                         
    "y":10,                 
    "z":0,
    "type":"BLOOD",
    "discovered":false,
    "scene_id":"d00fb22e-a352-4554-849e-929d957fe24c"
}

###
get {{host}}/simulation/evidence

###
put {{host}}/simulation/evidence
Content-Type: application/json

{
    "discovered":true,
    "id":"e9471416-4bad-4aa2-b42f-d47fddc1af40",
    "event_id":"e380b2dc-e6b4-45c3-bb6f-3ee78486aaf5"
}
###
post {{host}}/simulation/event
Content-Type: application/json

{
    "action":"Spotted evidence.",                         
    "session_id":"0926a1bf-181d-413f-b9c4-b2ea9df9f72d",
    "glasses":"440",
    "filter":"440"
}
###
put {{host}}/simulation/event
Content-Type: application/json

{
    "id":"e380b2dc-e6b4-45c3-bb6f-3ee78486aaf5",                   
    "user_id":"ac89db60-898e-4059-b7eb-77c1fa8b11b4"
}


# Make server public
# Write documentation


